name: microservices
services:
  backend:
    container_name: backend
    build: ./src/backend
    ports:
      - "127.0.0.1:5000:5000"
  frontend:
    container_name: frontend
    build: ./
    command: ["bash", "-c", "npm install && npm run dev"]
    ports:
      - 8080:8080
    volumes:
      - ./src/frontend:/src/frontend
    # Override the default stop signal
    stop_signal: SIGKILL
  