CREATE TYPE INVITE_STATUS AS ENUM ('YES', 'NO', 'MAYBE', 'PENDING');
CREATE TABLE "invites" (
    "eventId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,
    "status" INVITE_STATUS NOT NULL DEFAULT 'PENDING',
    PRIMARY KEY ("eventId", "userId") -- FOREIGN KEY ("eventId") REFERENCES "events" ("id") ON DELETE CASCADE,
    -- FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE
);
